#!/bin/sh
set -e

psql -v ON_ERROR_STOP=1 --username="$POSTGRES_USER" --dbname="$POSTGRES_DB" <<-EOSQL
    CREATE USER rwhead WITH ENCRYPTED PASSWORD 's1em1e_ln1ane' NOCREATEDB;

    CREATE TABLE "user" (
        uid integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        nick varchar(64) NOT NULL,
        email varchar(256) NOT NULL,
        passhash varchar(182) NOT NULL,
        provenance varchar(256),
        motto varchar(256),
        user_creation_timestamp timestamp(3) with time zone DEFAULT now() NOT NULL
    );

    CREATE TABLE "user_role" (
        uid integer PRIMARY KEY REFERENCES "user"(uid) NOT NULL,
        role integer NOT NULL DEFAULT 0
    );

    CREATE TABLE "user_settings" (
        uid integer PRIMARY KEY REFERENCES "user"(uid) NOT NULL,
        display_email boolean NOT NULL DEFAULT true
    );

    CREATE TABLE "topic" (
        tid integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        uid integer REFERENCES "user"(uid) NOT NULL,
        topic_creation_timestamp timestamp(3) with time zone DEFAULT now() NOT NULL,
        title varchar(256) NOT NULL,
        content text
    );

    CREATE TABLE "post" (
        pid integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        tid integer REFERENCES "topic"(tid) NOT NULL,
        uid integer REFERENCES "user"(uid) NOT NULL,
        post_creation_timestamp timestamp(3) with time zone DEFAULT now() NOT NULL,
        title varchar(256) NOT NULL,
        content text,
        score integer NOT NULL DEFAULT 0
    );

    CREATE TABLE "comment" (
        cid integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        pid integer REFERENCES "post"(pid) NOT NULL,
        uid integer REFERENCES "user"(uid) NOT NULL,
        comment_creation_timestamp timestamp(3) with time zone DEFAULT now() NOT NULL,
        content text,
        score integer NOT NULL DEFAULT 0
    );

    GRANT USAGE ON SCHEMA public TO rwhead;
    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO rwhead;
    GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO rwhead;
    GRANT EXECUTE ON ALL PROCEDURES IN SCHEMA public TO rwhead;
    GRANT EXECUTE ON ALL ROUTINES IN SCHEMA public TO rwhead;
EOSQL